---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - apps.mashibing.com
  resources:
  - msbdeployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.mashibing.com
  resources:
  - msbdeployments/finalizers
  verbs:
  - update
- apiGroups:
  - apps.mashibing.com
  resources:
  - msbdeployments/status
  verbs:
  - get
  - patch
  - update
