apiVersion: v1
kind: Service
metadata:
  name: {{ .ObjectMeta.Name }}
spec:
  type: NodePort
  selector:
    app: {{ .ObjectMeta.Name }}
  ports:
    - port: {{ .MSbDeploymentSpec.Port }}
      targetPort: {{ .MSbDeploymentSpec.Port }}
      nodePort: {{ .MSbDeploymentSpec.Expose.NodePort }}